### ISSUE TITLE
Bug: User-Agent=August/Luna-3.2.2 throws 403 on non-US country

### ISSUE THREAD

**Issue by matteozambon89** [donavanbecker/august-yale#13]
### Describe The Bug

When calling authorize on non-US country code, the session request fails with a 403. By commenting out the User-Agent at src/util/session.ts:18 the problem is solved.

### To Reproduce

Use a yale account in non-US (e.g. IE or UK), attempt to authorize and a 403 happens

### Expected behavior

Authorizing with non-US country (e.g. IE) should authorize and send the code to the email/phone number

### Relevant log output

```shell
No logs except the 403 error.
```

### Config for August-Yale

```shell
{
  "installId": "***", // replace with a random UUID
  "augustId": "***@***.com", // replace with your email
  "password": "***", // replace with your password
  "countryCode": "IE"
}
```

### Device & Model

Any

### Node.js Version

18 and 21

### August-Yale Version

1.1.0

### Operating System

Docker

**Comment by donavanbecker** [comment]
removed in v1.1.1
