### ISSUE TITLE
Bug/Issue: Swallowing Errors

### ISSUE THREAD

**Issue by joeybaker** [donavanbecker/august-yale#3]
### Describe The Bug

The `fetch` method intentionally swallows errors, which messes up stack traces and logging

### To Reproduce

Have any request fail, you'll get the `console.error` but without a stack trace, which when running this in a more complex environment is easy to miss and hard to trace

### Expected behavior

Things are working as intended, but they probably should work differently in dev and prod

### Relevant log output

```shell
No relevant logs beyond what was described.
```

### Config for August-Yale

```shell
n/a
```

### Screenshots

FWIW, I ran into this because home bridge was in a crash loop (for completely unrelated reasons). This caused _a lot_ of requests to go out through the homebridge plugin that wraps this library and this triggered a rate limit. I then had to trace down _why_ august was failing and because this bypasses the standard homebridge logging with `console.error`, that was not easy. 

I'd suggest (and am happy to PR) either:

1. Adding a dev mode that keeps this behavior if opted into only.
2. Just removing this bypass and letting the error bubble up.

### Device & Model

n/a

### Node.js Version

v20.11.0

### August-Yale Version

v0.2.0

### Operating System

macOS

**Comment by donavanbecker** [comment]
@joeybaker please open a PR. I opened this to be able to mange the API module myself and to use it in typescript.

**Comment by donavanbecker** [comment]
Please open PRs and point towards `beta` branch.

**Comment by joeybaker** [comment]
@donavanbecker done! ^

**Comment by donavanbecker** [comment]
Merged!
