### ISSUE TITLE
Feature Request: limit the number of concurrent session requests

### ISSUE THREAD

**Issue by joeybaker** [donavanbecker/august-yale#4]
### Problem

It's possible to trigger multiple session calls to get an api token concurrently. This is a bit of a waste, we could be smarter and not trigger multiple requests if one is already in-flight.

### Solution

I'd suggest hanging on to the request promise and let subsequent calls to `session` await the same promise. I'd be happy to put up a PR if you're interested.

**Comment by donavanbecker** [comment]
@joeybaker Yes please open a PR

**Comment by donavanbecker** [comment]
Please open PRs and point towards `beta` branch.

**Comment by joeybaker** [comment]
@donavanbecker done! ^

**Comment by donavanbecker** [comment]
Merged. Will get this beta on the Homebridge-August beta!
